-- Création du rôle pour DBT
CREATE ROLE IF NOT EXISTS DBT_ROLE;

-- Droits sur le Warehouse
GRANT USAGE ON WAREHOUSE NYC_TAXI_WH TO ROLE DBT_ROLE;

-- Droits sur la Database et les Schemas
GRANT USAGE ON DATABASE NYC_TAXI TO ROLE DBT_ROLE;
GRANT USAGE ON SCHEMA NYC_TAXI.RAW TO ROLE DBT_ROLE;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA NYC_TAXI.STAGING TO ROLE DBT_ROLE;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA NYC_TAXI.MART TO ROLE DBT_ROLE;